name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  lint-and-test:
    name: python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.12"
          enable-chache: true
          cach-dependecy-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Ruff formatting
        run: uv run ruff format --check .

      - name: Ruff linting
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest
